version: '3.8'

services:
  app:
    build: .
    container_name: order-service
    ports:
      - '3000:3000'
    environment:
      - MONGO_URI=mongodb://root:example@mongo:27017/order-service?authSource=admin
      - JWT_SECRET=your_jwt_secret